language:
    node_js

node_js:
    - "0.10"

addons:
  firefox: "28.0"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give server some time to start

script:
    - bower install
    #run tests on travis with firefox as the only supported
    #browser by travis. note that currently phantomjs fail
    #also avoid generating coverage
    - grunt --verbose test:travisCI
